x-base_service: &base_service
    stop_signal: SIGKILL
    tty: true
    restart: unless-stopped
    deploy:
      resources:
#        limits:
#          cpus: 8
#          memory: 48G
        reservations:
#          cpus: 4
#          memory: 24G
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility, gpu]

x-auto_service: &auto_service
    <<: *base_service
    container_name: auto
    build: ./services/AUTOMATIC1111
    image: sd-auto:78
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  auto:
    <<: *auto_service
    profiles: ["auto"]
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

# TODO check docker image
#  auto-rocm:
#    <<: *base_service
#    profiles: ["auto-rocm"]
#    image: simonmcnair/automatic1111-rocm:master
#    devices:
#      - "/dev/kfd"
#      - "/dev/dri"
#    deploy: {}
#    environment:
#      - CLI_ARGS=--allow-code --medvram --enable-insecure-extension-access --api
#
#  reforge: &reforge
#    <<: *base_service
#    profiles: ["reforge"]
#    image: simonmcnair/reforge:master
#    environment:
#      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api --pin-shared-memory --cuda-malloc --cuda-stream
#
#  forge: &forge
#    <<: *base_service
#    profiles: ["forge"]
#    image: simonmcnair/forge:master
#    environment:
#      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api --pin-shared-memory --cuda-malloc --cuda-stream
#
#  fooocus: &fooocus
#    <<: *base_service
#    profiles: ["fooocus"]
#    image: simonmcnair/fooocus:master
#    environment:
#      - CLI_ARGS=

  auto-cpu:
    <<: *auto_service
    profiles: ["auto-cpu"]
    deploy: {}
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  auto-full:
    <<: *auto_service
    profiles: [ "full" ]
    environment:
      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --no-half-vae --api

  comfy: &comfy
    <<: *base_service
    profiles: ["comfy"]
    container_name: comfy
    build: ./services/comfy
    image: sd-comfy:7
    volumes:
      - ./data/models:/opt/comfyui/models
      - ./data/config/comfy/custom_nodes:/opt/comfyui/custom_nodes
      - ./output/comfy:/opt/comfyui/output
      - ./data/models/configs:/opt/comfyui/user/default/
    ports:
      - "${COMFYUI_PORT:-7861}:7861"
    environment:
      - COMFYUI_PATH=/opt/comfyui
      - COMFYUI_MODEL_PATH=/opt/comfyui/models
      - CLI_ARGS=
#      - TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD=1

  comfy-cpu:
    <<: *comfy
    profiles: ["comfy-cpu"]
    deploy: {}
    ports:
      - "${COMFYUI_PORT:-7861}:7861"
    environment:
      - CLI_ARGS=--cpu

  swarmui:
    <<: *base_service
    profiles: ["swarmui"]
    container_name: swarmui
    build: ./services/swarmui
    image: sd-swarmui
    ports:
      - "${SWARMUI_PORT:-7801}:7801"
    volumes:
      - ./data/swarmui:/SwarmUI/Data
#      - "backend:/app/dlbackend"
      - ./data/models:/SwarmUI/Models
      - ./output/swarmui:/SwarmUI/Output

  convertor:
    <<: *base_service
    profiles: [ "convert" ]
    build: ./services/convert2safetensors
    image: sd-convert
    volumes:
      - ./data/convert:/opt/convert2safetensors/models
